### ISSUE TITLE
App logo

### ISSUE THREAD

**Issue by natesheehan** [Indicative-Data-Science/gnsscollecter#3]
<img width="490" alt="GNSS" src="https://user-images.githubusercontent.com/22789869/122674460-3ef9ef00-d1cd-11eb-8229-c017a9ee0c63.png">

**Comment by natesheehan** [comment]
Initial design - unsure on what we want to call this application (@TerryLines & @mrsensible ) ?

**Comment by natesheehan** [comment]
https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=android&foreground.space.trim=1&foreground.space.pad=0.25&foreColor=rgba(96%2C%20125%2C%20139%2C%200)&backColor=rgb(68%2C%20138%2C%20255)&crop=0&backgroundShape=square&effects=none&name=ic_launcher

**Comment by dataandcrowd** [comment]
The logo seems really nice and simple!
Would it be nice if we put the full name below the GNSS for the general public or something like:

```
GNSS
To Recreate our Urban System
```
Branding is the most difficult part of the development right? :-)

**Comment by natesheehan** [comment]
<img width="407" alt="gnss-logo4" src="https://user-images.githubusercontent.com/22789869/123074984-b323d500-d40f-11eb-86cd-818b2f3f1f5c.png">
<img width="306" alt="gnss-logo2" src="https://user-images.githubusercontent.com/22789869/123074991-b4ed9880-d40f-11eb-8f58-24651b20e4a8.png">
<img width="446" alt="gnss-logo3" src="https://user-images.githubusercontent.com/22789869/123074993-b5862f00-d40f-11eb-8105-e1ad5c9b40d4.png">

**Comment by natesheehan** [comment]
A few more mock ups! And yes , you're very correct @mrsensible, its made even more difficult when your a developer pretending to be a designer 😆
